name: "Jones Lab"
description: "This is the official web page for Jones Lab at Pitt."

url: "https://pitt-joneslab.github.io/"

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/

collections:
        members:
                output: true
        publications:
                output: true
        undergrads:
                output: true
        new:
                output: true
        grads-phd:
                output: true
        grads-ms:
                output: true
        alumni-bottom:
                output: true
        

